### PR TITLE
restore deleteFactor test

### PR DESCRIPTION
**Pull request by dehann**
trying to restore the deleteFactor test.

### CODE REVIEW

**Comment by dehann** [comment]
HI Johan, if you could check with Jim how to fix if you're having trouble with this one please.

**Comment by Affie** [comment]
It worked yesterday, the only test that failed was in `initVariable`

**Comment by dehann** [comment]
- https://github.com/NavAbility/NavAbilitySDK.jl/pull/163

**Comment by dehann** [comment]
i added the few fixes needed, thanks

**Pull request merged**
