### PR TITLE
restore export session test

### PR DESCRIPTION
**Pull request by dehann**
trying to restore previously working export session test

### CODE REVIEW

**Comment by dehann** [comment]
Thanks for taking.  I'm currently exporting graphs manually by using NavAbilityCaesarExtensions and DFG.copyGraph!.  It works well enough for early dev but will become a bigger time sink as we start to push bigger graphs and solves.  Im currently limiting Hilti work to around 50-100 variables.

**Comment by GearsAD** [comment]
Dang, sorry, I converted this to a full PR by accident.

**Comment by jim-hill-r** [comment]
Is this still relevant? Sorry its just been awhile.

**Comment by dehann** [comment]
Yes

**Comment by dehann** [comment]
Okay @jim-hill-r , message received.

cc @GearsAD

**Comment by jim-hill-r** [comment]
Closing as stagnant.

**Pull request closed without merging**
