### PR TITLE
Test 1D and Mixture,

### LINKED ISSUE #79: Tests for 1D and Mixture cases.
There are not integration tests for these cases and there should be some before we tag this release.

### PR DESCRIPTION
**Pull request by dehann**
closes #79

### CODE REVIEW

**Review by sam-globus — APPROVED** [review]
LGTM, just curious, why aren't you solving it? Does it solve?

**Comment by sam-globus** [comment]
Ah wait one, that doesn't do a Mixture test - if you want, split that into another issue.

**Comment by dehann** [comment]
we can add the solve, I was sending solves to make sure it runs through.  PPEs came back.  Did not triple check the numerics, but PPEs are there and looked right.

I took out the solving because the request is sent and the test closes out while the server is still processing the solve.  So seemed excessive to have the test pass while the solve is still ongoing.  Hence the doSolve flag, we can just make that true if you think it will help?

**Comment by dehann** [comment]
Screenshot from 2022-03-29 20-00-25

**Comment by dehann** [comment]
```julia
julia> getVariables(client, context; detail=SUMMARY) .|> x->x["ppes"][1]["suggested"]
4-element Vector{Vector{Any}}:
 [-40.186702018171744]
 [9.711123006149444]
 [9.729649698600467]
 [-0.21231469666968547]

julia> context
Client: User=Guest, Robot=SDKJL1D, Session=TestSession4

```

**Comment by GearsAD** [comment]
Cool, yep I'd say it's good to go for now (we can refactor further as we improve tests) but LGTM. 

Regarding the solve, I'm half and half - the waitForCompletion should wait for a solve, so it will solve before completing. However we're not testing anything from the results, so it's not necessary at the moment. I'd say leave as it is and we can grow the tests as we add more.

**Review by GearsAD — APPROVED** [review]

**Pull request merged**
